version: "3.0"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      GUNICORN_CMD_ARGS: "--bind=0.0.0.0:8000 --workers=3"

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      PORT: 5000
      NODE_ENV: production
    depends_on:
      - api
    volumes:
      - static:/app/build

# Not actually used, here for demonstration purposes.
volumes:
  static:
